In [2]:
import pandas as pd 
import sqlite3
import country_converter as coco
import numpy as np 
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

DATA = 'covid.db'

conn = sqlite3.connect(DATA)
# Planning 
"""
Line Graphs: 
1. Cumulative total cases AND Daily_new_cases; draw active_cases in both
2. Cumulative total deaths 

Choroph Plot: 
1. Cumulative_total_cases 
2. Cumulative_total_deaths

Animated Bar Chart
1. Daily_new_cases 
2. Daily_new_deaths 
-> This is to see the top 20 countries with high cumulative_total_cases, 
who has effectively controlled the spread of COVID
"""

'\nLine Graphs: \n1. Cumulative total cases AND Daily_new_cases; draw active_cases in both\n2. Cumulative total deaths \n\nChoroph Plot: \n1. Cumulative_total_cases \n2. Cumulative_total_deaths\n\nAnimated Bar Chart\n1. Daily_new_cases \n2. Daily_new_deaths \n-> This is to see the top 20 countries with high cumulative_total_cases, \nwho has effectively controlled the spread of COVID\n'

## Data overview

In [3]:
# Loading Data 
query = """
SELECT * 
FROM covid_cases
"""

df = pd.read_sql(query, conn)
# Renaming active_cases to daily_active_cases, for clarification 
df.rename(columns={'active_cases': "daily_active_cases"}, inplace=True)

df.describe() # All countries except China begins at this date

,cumulative_total_cases,daily_new_cases,daily_active_cases,cumulative_total_deaths,daily_new_deaths,death_rate
count,1.847870e+05,184787.000000,1.667470e+05,1.782270e+05,175767.000000,1.705450e+05
mean,7.251089e+05,2818.548507,6.239283e+04,1.388600e+04,35.771533,inf
std,3.681471e+06,17305.881476,3.955641e+05,6.049521e+04,172.046845,NaN
min,0.000000e+00,-322.000000,-1.432100e+04,0.000000e+00,-39.000000,0.000000e+00
25%,1.099000e+03,0.000000,6.000000e+01,2.400000e+01,0.000000,7.511267e-01
50%,1.775600e+04,41.000000,1.386000e+03,3.040000e+02,0.000000,1.530272e+00
75%,2.238085e+05,636.000000,1.462050e+04,4.111000e+03,9.000000,2.669188e+00
max,8.420947e+07,909610.000000,1.793543e+07,1.026646e+06,5093.000000,inf

Observations: 
- There are negative values for daily new cases, active cases, and new deaths. This will need to be further investigated 
- The standard deviation for 4 variables are quiet large
- The range for all 4 variables from MIN to MAX is large, therefore they will be rescaled

In [4]:
print(df.dtypes)
print('-' * 100)
print("The dataset contains statistical records for ", len(df.country.unique()), "countries")
print("There are :", df.isna().sum().sum(), "Null values")

date                        object
country                     object
cumulative_total_cases     float64
daily_new_cases            float64
daily_active_cases         float64
cumulative_total_deaths    float64
daily_new_deaths           float64
country_ISO3                object
death_rate                 float64
dtype: object
----------------------------------------------------------------------------------------------------
The dataset contains statistical records for  226 countries
There are : 47862 Null values

- Need a new column for ISO-3 format of country names. 
- 61995 Null values will need to be investigated

# Data Processing

In [6]:
# ------------ Negative values ------------------ 

df[(df.daily_new_cases < 0) | (df.daily_new_deaths < 0) | (df.daily_active_cases < 0)]  
# For these varables, the negatives will be clipped to 0, to prevent 
"""
Because it is not logical to have negative daily new cases, new deaths and active cases, they cannot un-die or get un-sick.
Therefore these variables will be clipped to 0, to prevent any misleading spikes downward. 
"""
query = """
UPDATE covid_cases

SET
    daily_new_cases = MAX(daily_new_cases, 0),
    daily_new_deaths= MAX(daily_new_deaths, 0),
    active_cases= MAX(active_cases, 0) 

"""
query = """
SELECT *
FROM covid_cases
"""

df = pd.read_sql(query, conn)
df[(df.daily_new_cases < 0) | (df.daily_new_deaths < 0) | (df.daily_active_cases < 0)]

,date,country,cumulative_total_cases,daily_new_cases,daily_active_cases,cumulative_total_deaths,daily_new_deaths,country_ISO3,death_rate
590,2021-09-27,Afghanistan,155093.0,-39.0,23879.0,7201.0,3.0,AFG,4.643021
631,2021-11-07,Afghanistan,156365.0,-32.0,20124.0,7287.0,3.0,AFG,4.660250
661,2021-12-07,Afghanistan,157509.0,23.0,8990.0,7316.0,-1.0,AFG,4.644814
13574,2021-05-14,Barbados,3961.0,2.0,-3.0,48.0,0.0,BRB,1.211815
13576,2021-05-16,Barbados,3967.0,2.0,-3.0,48.0,0.0,BRB,1.209982
...,...,...,...,...,...,...,...,...,...
172770,2020-11-24,Uganda,22278.0,292.0,-1302.0,316.0,8.0,UGA,1.418440
172771,2020-11-25,Uganda,22864.0,586.0,-904.0,324.0,8.0,UGA,1.417075
172772,2020-11-26,Uganda,23136.0,272.0,-653.0,324.0,0.0,UGA,1.400415
172773,2020-11-27,Uganda,23709.0,573.0,-90.0,334.0,10.0,UGA,1.408748
175825,2020-04-13,Uruguay,483.0,-29.0,227.0,8.0,1.0,URY,1.656315

In [21]:
# ----------------- NULL Values ------------------------
"""
For the NULL values appearing before the first daily_new_cases, active_cases, c
umulative_total_deaths, and daily_new_deaths,
they will be setted to 0
"""
query_first_date = """
SELECT
    country,
    MIN(CASE WHEN daily_new_cases > 0 THEN date END) AS first_case_date,
    MIN(CASE WHEN daily_new_deaths > 0 THEN date END) AS first_death_date,
    MIN(CASE WHEN active_cases > 0 THEN date END) AS first_active_case_date,
    MIN(CASE WHEN cumulative_total_cases > 0 THEN date END) AS first_total_case_date,
    MIN(CASE WHEN cumulative_total_deaths > 0 THEN date END) AS first_total_death_date   
FROM covid_cases
GROUP BY country
"""
query = """
SELECT * 
FROM covid_cases
"""
df_first_date = pd.read_sql(query_first_date, conn)
df = pd.read_sql(query, conn)

df = df.merge(df_first_date, on='country', how='left')

df['daily_new_cases'] = np.where(
    df['date'] < df['first_case_date'], 0, df['daily_new_cases']
)

df['daily_new_deaths'] = np.where(
    df['date'] < df['first_death_date'], 0, df['daily_new_deaths']
)

df['active_cases'] = np.where(
    df['date'] < df['first_active_case_date'], 0, df['active_cases']
)

df['cumulative_total_cases'] = np.where(
    df['date'] < df['first_total_case_date'], 0, df['cumulative_total_cases']
)

df['cumulative_total_deaths'] = np.where(
    df['date'] < df['first_total_death_date'], 0, df['cumulative_total_deaths']
)


df.head()
df.to_sql(name='covid_cases', con=conn, if_exists='replace', index=False)

DatabaseError: Execution failed on sql '
SELECT
    country,
    MIN(CASE WHEN daily_new_cases > 0 THEN date END) AS first_case_date,
    MIN(CASE WHEN daily_new_deaths > 0 THEN date END) AS first_death_date,
    MIN(CASE WHEN active_cases > 0 THEN date END) AS first_active_case_date,
    MIN(CASE WHEN cumulative_total_cases > 0 THEN date END) AS first_total_case_date,
    MIN(CASE WHEN cumulative_total_deaths > 0 THEN date END) AS first_total_death_date
FROM covid_cases
GROUP BY country
': no such column: active_cases

In [7]:
# ----------------- Convert Country to ISO3 Format --------------------
all_countries = df['country'].unique()  
iso3_mapping = {name: coco.convert(names=name, to='ISO3') for name in all_countries}


df['country_ISO3'] = df['country'].map(iso3_mapping)

Channel Islands not found in regex

In [8]:
df.sample(10)

,date,country,cumulative_total_cases,daily_new_cases,daily_active_cases,cumulative_total_deaths,daily_new_deaths,country_ISO3,death_rate
72239,2020-04-10,Guyana,37.0,0.0,23.0,6.0,0.0,GUY,16.216216
178755,2021-07-27,Vanuatu,4.0,0.0,0.0,1.0,0.0,VUT,25.000000
8584,2021-03-05,Australia,29021.0,14.0,53.0,947.0,0.0,AUS,3.263154
23263,2020-12-14,Brunei Darussalam,152.0,0.0,2.0,3.0,0.0,BRN,1.973684
167572,2020-02-20,Togo,0.0,0.0,0.0,0.0,0.0,TGO,NaN
106638,2020-02-29,Mayotte,0.0,0.0,0.0,0.0,0.0,MYT,NaN
123950,2020-05-31,Norway,8440.0,3.0,NaN,237.0,0.0,NOR,2.808057
116764,2020-12-11,Nauru,0.0,0.0,0.0,NaN,NaN,NRU,NaN
178975,2022-03-04,Vanuatu,30.0,1.0,23.0,1.0,0.0,VUT,3.333333
108120,2021-12-22,Mexico,3937082.0,2980.0,346815.0,298161.0,245.0,MEX,7.573147

In [9]:
# ----------------- Re-scaling Data --------------------

# I applied a log scale in the plot to clearly visualize data that spans several orders of magnitude, 
# without altering the original dataset.


# ----------------- Calculating Death Rate ---------------------
df['death_rate'] = (df['cumulative_total_deaths'] / df['cumulative_total_cases']) * 100
df.sample(5)

,date,country,cumulative_total_cases,daily_new_cases,daily_active_cases,cumulative_total_deaths,daily_new_deaths,country_ISO3,death_rate
154346,2022-02-03,South Africa,3616075.0,3266.0,54849.0,95545.0,82.0,ZAF,2.642229
51375,2021-07-10,Egypt,282985.0,121.0,48846.0,16383.0,15.0,EGY,5.789353
156594,2021-07-06,Spain,3880612.0,14137.0,173260.0,80952.0,18.0,ESP,2.086063
131968,2021-06-10,Portugal,855368.0,914.0,NaN,17033.0,6.0,PRT,1.991307
123318,2020-12-05,Niue,0.0,0.0,0.0,NaN,NaN,NIU,NaN

In [11]:
# # ------------------- Final Modifications -----------------------
# df.drop(columns=['first_death_date', 'first_active_case_date', 'first_total_case_date', 
#                  'first_total_death_date', 'first_case_date'], inplace=True)

df.to_sql(name='covid_cases', con=conn, if_exists='replace', index=False)

184787

In [14]:
df.sample(5)

,date,country,cumulative_total_cases,daily_new_cases,daily_active_cases,cumulative_total_deaths,daily_new_deaths,country_ISO3,death_rate
129739,2022-01-27,Peru,3120401.0,50044.0,NaN,204940.0,171.0,PER,6.567746
121930,2021-08-14,Niger,5722.0,3.0,93.0,196.0,0.0,NER,3.425376
73031,2020-03-13,Haiti,0.0,0.0,0.0,0.0,0.0,HTI,NaN
128136,2022-03-05,Papua New Guinea,41421.0,0.0,878.0,638.0,0.0,PNG,1.540281
121096,2021-07-31,Nicaragua,9470.0,0.0,5050.0,195.0,0.0,NIC,2.059134

In [15]:
conn.close()